{% set name = "optree" %}
{% set version = "0.15.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d00a45e3b192093ef2cd32bf0d541ecbfc93c1bd73a5f3fe36293499f28a50cf

build:
  number: 0
  skip: True  # [py<38]
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  script_env:
    - CMAKE_GENERATOR=Visual Studio 16 2019 # [win]
    - _GLIBCXX_USE_CXX11_ABI=1
  missing_dso_whitelist:  # [s390x]
    - $RPATH/ld64.so.1    # [s390x]

requirements:
  build:
    - python                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - cmake >=3.18  # to support `CMAKE_GENERATOR`
    - make                                # [not win]
  host:
    - pip
    - python
    - setuptools
    - wheel
    - pybind11 >=2.12
  run:
    - python
    - typing-extensions >=4.5.0

test:
  imports:
    - optree
  source_files:
    - tests
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - pytest -W always -W error tests

about:
  home: https://github.com/metaopt/optree
  summary: Optimized PyTree Utilities
  description: Optimized PyTree Utilities.
  dev_url: https://github.com/metaopt/optree
  doc_url: https://optree.readthedocs.io
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE

extra:
  recipe-maintainers:
    - XuehaiPan
